In [1]:
!pip install gensim

In [2]:
from gensim.models import word2vec
import numpy as np
import gensim
from multiprocessing import cpu_count
#model = Word2Vec(sentences, min_count = 0, workers=cpu_count())

In [3]:
cpu_count()

4

In [7]:

sentences = word2vec.Text8Corpus('text8')

In [8]:
sentences

In [9]:
model = word2vec.Word2Vec(sentences, size=100,min_count=2)

In [10]:
model.wv.vocab

{'anarchism': <gensim.models.keyedvectors.Vocab at 0x240233675c0>,
 'originated': <gensim.models.keyedvectors.Vocab at 0x24023367898>,
 'as': <gensim.models.keyedvectors.Vocab at 0x24023367a20>,
 'a': <gensim.models.keyedvectors.Vocab at 0x24023367a90>,
 'term': <gensim.models.keyedvectors.Vocab at 0x24023367d30>,
 'of': <gensim.models.keyedvectors.Vocab at 0x24023367d68>,
 'abuse': <gensim.models.keyedvectors.Vocab at 0x24023367e10>,
 'first': <gensim.models.keyedvectors.Vocab at 0x240230f26a0>,
 'used': <gensim.models.keyedvectors.Vocab at 0x240230f2cf8>,
 'against': <gensim.models.keyedvectors.Vocab at 0x240231e6748>,
 'early': <gensim.models.keyedvectors.Vocab at 0x240231e6be0>,
 'working': <gensim.models.keyedvectors.Vocab at 0x24023314eb8>,
 'class': <gensim.models.keyedvectors.Vocab at 0x240233142e8>,
 'radicals': <gensim.models.keyedvectors.Vocab at 0x24023314588>,
 'including': <gensim.models.keyedvectors.Vocab at 0x240233146a0>,
 'the': <gensim.models.keyedvectors.Vocab at 0x

In [11]:
len(model.wv.vocab)

135335

In [12]:
model['class']

E:\INSTALACIONES\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.6589999 ,  2.8185098 ,  0.6615088 , -1.456958  ,  0.2892753 ,
        1.2207696 ,  0.5357424 , -0.50698006,  0.26698565,  1.0945313 ,
       -1.4717277 ,  0.34428898,  0.55999315, -0.135147  ,  0.8714859 ,
        0.16496791, -3.3551044 , -1.8722944 ,  0.02872578, -1.0573537 ,
        0.3814562 , -1.734128  ,  0.8003206 ,  0.5045592 ,  0.9481195 ,
       -1.2007481 ,  1.5426503 ,  0.5227186 , -2.2122931 ,  1.2256889 ,
       -0.5270544 , -0.8546453 , -0.12004264, -0.59044904,  1.1597546 ,
       -2.5363414 , -2.0898912 ,  3.4289672 , -2.185738  , -0.5964662 ,
        1.2667061 ,  0.1313406 ,  1.407604  ,  0.2756035 ,  0.4677175 ,
       -2.169066  ,  0.73897   ,  1.3876919 ,  0.54902047,  1.328411  ,
        2.3902454 ,  0.0633279 ,  2.5558903 ,  0.9847482 , -0.1260036 ,
        0.4631771 , -2.6378634 , -0.2884486 , -0.10644365,  0.69597137,
        0.4285388 , -1.9660329 , -0.13396649, -1.6748137 , -0.65756327,
        0.43905056,  0.48118755,  0.3650309 , -1.3832607 , -0.79

In [13]:
model["king"]

E:\INSTALACIONES\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-1.7225795e+00,  2.3786581e+00,  1.7929997e+00, -1.7545713e+00,
       -8.8515586e-01, -1.6767830e+00, -7.0639633e-02, -2.9944124e+00,
       -5.8216280e-01, -5.6142962e-01,  2.0254228e-01, -3.9106951e+00,
        5.4368908e-03, -4.6497193e-01, -3.3789747e+00,  2.9919770e+00,
       -1.2497224e-01,  2.1046319e+00,  1.0976642e+00,  2.3406022e-03,
       -1.7508785e+00, -3.0963027e-01,  1.0036834e+00,  2.3336675e+00,
        2.5827056e-01, -1.7154812e+00, -7.9355848e-01,  5.9617090e-01,
        8.4696549e-01, -2.3963308e+00, -1.3243940e+00,  6.3377488e-01,
       -3.0524566e+00,  7.8787012e-03,  1.4756904e+00, -3.7240583e-01,
       -2.2028623e+00, -1.2281847e+00,  1.6426721e+00, -1.6795305e+00,
       -1.0646518e-01, -1.5419105e+00, -1.9154992e+00,  1.2332815e+00,
       -2.5432894e+00, -9.6065515e-01, -5.6491560e-01,  1.6767733e-01,
       -8.7973303e-01, -1.6946622e+00, -8.6414063e-01,  4.3300137e-01,
        5.2546608e-01,  9.9281454e-01,  2.2583856e-01,  2.4374294e+00,
      

In [14]:
model.most_similar(positive=["king"],topn=10)

E:\INSTALACIONES\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('prince', 0.7628257274627686),
 ('emperor', 0.7341145277023315),
 ('queen', 0.7128743529319763),
 ('throne', 0.6944755911827087),
 ('kings', 0.6919008493423462),
 ('aragon', 0.6892908215522766),
 ('vii', 0.6882935762405396),
 ('duke', 0.6728622913360596),
 ('constantine', 0.666812539100647),
 ('regent', 0.658867597579956)]

In [15]:
model["bands"]

E:\INSTALACIONES\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-0.14297439, -0.1204308 ,  0.7413859 ,  0.6042979 , -1.0372571 ,
        1.5421646 , -0.47767305,  1.3679136 ,  0.39776266, -0.40480325,
        2.0303707 , -2.251684  ,  1.0385919 , -0.54582244, -0.6704394 ,
       -0.53455305,  0.17505957, -1.9215682 ,  0.53554225,  0.352359  ,
       -0.25822717,  0.4486758 , -2.672482  , -0.21488991, -0.88941604,
       -0.6418689 , -0.47069147,  0.46156397,  0.91513664,  1.2504683 ,
        2.2325513 , -0.49686605,  1.5937005 , -2.135455  , -1.5093255 ,
        1.2216743 ,  1.1516169 , -0.52399147, -1.5303844 ,  2.022428  ,
        1.5258268 , -1.7869008 ,  0.24219242, -0.64514816,  0.78943646,
        1.3363844 ,  3.2136087 ,  0.84657794, -0.00865373,  1.5479888 ,
       -0.9014615 ,  1.2974492 ,  0.74760336, -0.35000318, -1.8390191 ,
       -0.5032294 , -0.12101866,  0.85526556, -1.5021601 ,  1.0736213 ,
       -0.18912947, -0.85099417,  0.4154903 , -0.3518387 , -0.75715286,
       -2.1569014 , -1.2151052 ,  1.0257972 ,  1.563314  , -0.25

In [16]:
len(model.wv.vocab)

135335

In [17]:
model.wv.vocab

{'anarchism': <gensim.models.keyedvectors.Vocab at 0x240233675c0>,
 'originated': <gensim.models.keyedvectors.Vocab at 0x24023367898>,
 'as': <gensim.models.keyedvectors.Vocab at 0x24023367a20>,
 'a': <gensim.models.keyedvectors.Vocab at 0x24023367a90>,
 'term': <gensim.models.keyedvectors.Vocab at 0x24023367d30>,
 'of': <gensim.models.keyedvectors.Vocab at 0x24023367d68>,
 'abuse': <gensim.models.keyedvectors.Vocab at 0x24023367e10>,
 'first': <gensim.models.keyedvectors.Vocab at 0x240230f26a0>,
 'used': <gensim.models.keyedvectors.Vocab at 0x240230f2cf8>,
 'against': <gensim.models.keyedvectors.Vocab at 0x240231e6748>,
 'early': <gensim.models.keyedvectors.Vocab at 0x240231e6be0>,
 'working': <gensim.models.keyedvectors.Vocab at 0x24023314eb8>,
 'class': <gensim.models.keyedvectors.Vocab at 0x240233142e8>,
 'radicals': <gensim.models.keyedvectors.Vocab at 0x24023314588>,
 'including': <gensim.models.keyedvectors.Vocab at 0x240233146a0>,
 'the': <gensim.models.keyedvectors.Vocab at 0x

In [18]:
model["anarchism"]

E:\INSTALACIONES\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 1.09390926e+00,  7.93003023e-01, -2.81799287e-01,  5.18763721e-01,
       -5.55559337e-01,  1.13670863e-01, -8.80800188e-01,  1.68808103e+00,
        1.32363588e-01, -2.31141195e-01,  7.34233975e-01, -1.07992792e+00,
       -5.19329369e-01,  2.58209985e-02,  1.48801535e-01, -9.84746635e-01,
       -2.68286020e-01,  2.52296147e-03,  2.15533078e-01,  5.32903612e-01,
        1.65409577e+00, -4.63317841e-01, -1.36013412e+00, -4.71076518e-01,
        4.45566058e-01, -3.46158653e-01,  1.18528008e+00,  9.85655904e-01,
       -9.43312287e-01,  1.45883393e+00,  7.52400756e-01, -9.55140591e-01,
       -1.95823804e-01,  1.27150834e-01,  6.43441737e-01,  4.24514636e-02,
       -1.43922698e+00,  7.73466706e-01,  1.10429758e-02, -1.82237491e-01,
        8.35978746e-01, -7.23987579e-01,  1.67842078e+00, -5.27794480e-01,
       -1.45924234e+00, -1.23848535e-01,  2.67303556e-01, -4.08615470e-01,
        1.11779118e+00, -1.26865220e+00, -1.88909781e+00,  5.47416568e-01,
       -3.03133726e-01, -

In [19]:
model.most_similar(positive=['woman', 'king'], negative=['man'], topn=10)

E:\INSTALACIONES\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('queen', 0.6800137758255005),
 ('prince', 0.6503835916519165),
 ('emperor', 0.6382647752761841),
 ('son', 0.6329814195632935),
 ('empress', 0.6191946268081665),
 ('princess', 0.6056017875671387),
 ('daughter', 0.6021515727043152),
 ('throne', 0.5986530184745789),
 ('mary', 0.5964587330818176),
 ('elizabeth', 0.5952901840209961)]

In [20]:
model.most_similar(['man'])

E:\INSTALACIONES\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('woman', 0.7686231732368469),
 ('girl', 0.6798755526542664),
 ('creature', 0.6147236227989197),
 ('boy', 0.5796888470649719),
 ('person', 0.5679146647453308),
 ('beast', 0.5602870583534241),
 ('stranger', 0.5527347326278687),
 ('child', 0.5497643351554871),
 ('god', 0.5471939444541931),
 ('love', 0.5458770394325256)]

In [21]:
model.save('text8_1.model')

In [22]:
model.wv.save_word2vec_format('text2_2.model.bin', binary=True)

In [18]:
model1 = word2vec.KeyedVectors.load_word2vec_format('text2_2.model.bin', binary=True)

In [ ]:
model1["english"]

In [19]:
model1.most_similar(['girl', 'father'], ['boy'], topn=3)

[('mother', 0.788677990436554),
 ('wife', 0.7215999960899353),
 ('grandmother', 0.700046181678772)]

In [20]:
more_examples = ["he is she", "big bigger bad", "going went being"] 

In [21]:
for example in more_examples:
    a, b, x = example.split()
    predicted = model1.most_similar([x, b], [a])[0][0]
    print ("'%s' is to '%s' as '%s' is to '%s'" % (a, b, x, predicted))

'he' is to 'is' as 'she' is to 'remains'
'big' is to 'bigger' as 'bad' is to 'worse'
'going' is to 'went' as 'being' is to 'was'


In [23]:
model_org = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

FileNotFoundError: [Errno 2] No such file or directory: 'GoogleNews-vectors-negative300.bin'

In [18]:
model.most_similar('frog')

[('eyed', 0.8300723433494568),
 ('shark', 0.8163352012634277),
 ('rabbit', 0.8101553916931152),
 ('pink', 0.8050097227096558),
 ('crab', 0.8034614324569702),
 ('scarlet', 0.7912976145744324),
 ('hairy', 0.7898751497268677),
 ('winged', 0.7856602668762207),
 ('stuffed', 0.7845838665962219),
 ('swan', 0.7798329591751099)]

In [ ]:
s=0
for w in model.wv.vocab:
    s = s+model[w]
mean = s/len(model.wv.vocab)
mean

In [24]:
def getFV(document):
    
    words=document.split()
    s=np.zeros(200)
    k=0
    for w in words:
        if w in model1.wv.vocab:
            s=s+model1[w]
            k=k+1
    
    return s/k

In [25]:
getFV("english mother father")

array([-0.1920967 ,  0.72551737,  1.3305739 ,  1.1641924 ,  1.64354753,
        0.79011761,  0.13885144,  0.90280755, -0.17105255, -0.52310707,
       -0.86647597,  0.60541626,  1.27097277,  0.72853416, -1.08038698,
        0.71172499, -0.52265161, -1.82731958,  0.21499215, -0.4297265 ,
       -1.00684305,  0.19206845,  2.13171609, -0.1866451 , -0.21654577,
        0.88360703, -0.2212673 , -0.60284929,  0.23822799,  0.72744509,
        0.10942886,  0.20884407, -1.48303473, -0.29290565,  0.32880607,
        0.53292724,  0.66007203,  1.32958521, -0.8904136 , -0.42961011,
        0.04918588,  0.80693745,  0.48354395,  1.37055242,  0.31317511,
       -0.15162014, -0.01721211, -0.10252297, -0.35961006,  0.2806916 ,
        1.57799244,  1.93115596, -1.03218201,  0.26650229, -0.74519164,
       -1.61138872, -0.0553435 ,  0.77471318, -0.27091368,  0.53724706,
       -0.01296459, -2.7394017 , -0.61044884,  0.05606133, -1.12370396,
        1.40095318, -0.86684881,  1.02111252,  0.52151245,  0.21

In [27]:
sentences2 = word2vec.Text8Corpus(ççç)

In [28]:
model.build_vocab(sentences2,update=True)

In [29]:
model.train(sentences2,total_examples=model.corpus_count, epochs=model.iter)

1901

In [30]:
model["mundial"]

array([ 0.0460014 ,  0.08693243,  0.0198921 , -0.0639549 ,  0.02383695,
        0.01312263, -0.06710427, -0.09650418, -0.00638841, -0.03945454,
        0.03734591,  0.0221463 , -0.05016332,  0.04735284,  0.01347241,
       -0.03461092,  0.07906207,  0.01796186,  0.05596225,  0.01498506,
        0.01338899,  0.00857872, -0.01853392,  0.03992237, -0.01842699,
       -0.05239733,  0.11670461, -0.02744275,  0.08609854,  0.00498559,
        0.04633285,  0.03566618, -0.00902775,  0.04799515, -0.01413842,
       -0.03624701, -0.01162697, -0.01055149,  0.05933678,  0.02816383,
        0.04121719, -0.02386934, -0.07182215, -0.02831256, -0.03332881,
       -0.01028546, -0.08724254, -0.00781462, -0.00159442, -0.02844645,
       -0.02853785, -0.050718  , -0.03012423,  0.01588015,  0.03696628,
        0.04056194,  0.10336589,  0.01096868, -0.07848796,  0.03568391,
        0.0381955 , -0.03441605, -0.00330844, -0.00865895, -0.00877644,
        0.05837389, -0.03808545,  0.08126257, -0.00759991, -0.05

In [32]:
model.most_similar(["Claudio"])

[('Pizarro', 0.9904865026473999),
 ('volvería', 0.982028603553772),
 ('2021.', 0.9804888963699341),
 ('cual', 0.9800978302955627),
 ('Milan', 0.9779759645462036),
 ('Gianluigi', 0.9769549369812012),
 ('años,', 0.9758488535881042),
 ('razón', 0.975774884223938),
 ('Donnarumma,', 0.975178599357605),
 ('AC', 0.9751764535903931)]

In [ ]:
%%time
model.build_vocab(newwiki, update=True)
model.train(newwiki)
model.save('newmodel')
# model = Word2Vec.load('newmodel')